### PR TITLE
implement shot timer

### PR DESCRIPTION
**Pull request by echarlie**
This implements a basic timer (like the "timer" button on the distoX). Hold down A and the unit will count down in seconds. It can be configured to "0" (the previous default behaviour), 3, 5, or 10 seconds from the configuration menu. The default is 5.

### CODE REVIEW

**Comment by furbrain** [comment]
Please could you describe the use case for this feature. I'm not against having it, just want to understand how it will be used.

**Comment by echarlie** [comment]
For longer shots (over about 15m), blind shots, or shots that are likely to brush up against intermediate rocks/walls/debris, it is a lot more usable to trigger the countdown timer, then brace the unit against the from-station so that you get an accurate reading. Since the required force to trigger the buttons on the SAP6 is higher than a disto-type unit, it is especially useful, as pressing the button tends to result in drift due to muscle spasms or whatever.

Since the current default behaviour can kept by setting the timer to 0 (though I have set the default to 5s, which is that on the DistoX2), it just gives users an option.

**Comment by furbrain** [comment]
Ok, lets go ahead, but please could you change the default to 0 seconds (so current users don't get an unexpected change in behaviour). Please could you also update the documentation to reflect that, and I'll accept the PR.

**Comment by furbrain** [comment]
Please could you also confirm that these changes have been tested

**Comment by echarlie** [comment]
all changes I have made in my branches are tested before I commit, except for this most recent one setting the default value to 0. I can throw it on my device if you'd like, though.

I have updated the documentation to be more thorough.

**Comment by echarlie** [comment]
(I have bricked the device with a change once already and had to enter the circuitpython "safe mode", so suffice to say I am glad I'm testing before committing).

**Comment by furbrain** [comment]
Ok, all looks good. Merging. Thanks for your input - all very welcome.

Phil

**Pull request merged**
